### ISSUE TITLE
pasimple.exceptions.PaSimpleError: Error while creating stream: 3

### ISSUE THREAD

**Issue by henry-tujia** [henrikschnor/pasimple#4]
I encountered an error while attempting to record audio using the pasimple library in Python. The code provided below demonstrates my approach to capturing a 10-second audio sample from a specified ALSA device and saving it as a .wav file.

#### Error

```bash
Traceback (most recent call last):
  File "/workspace/tests/test_pasimple.py", line 11, in <module>
    with pasimple.PaSimple(
  File "/workspace/miniconda3/envs/whl_test/lib/python3.10/site-packages/pasimple/pa_simple.py", line 89, in __init__
    raise PaSimpleError(f'Error while creating stream: {error.value}')
pasimple.exceptions.PaSimpleError: Error while creating stream: 3
```

#### Code

```python
import wave
import pasimple

# Audio attributes for the recording
FORMAT = pasimple.PA_SAMPLE_U8
SAMPLE_WIDTH = pasimple.format2width(FORMAT)
CHANNELS = 1
SAMPLE_RATE = 48000

# Record 10 seconds of audio
with pasimple.PaSimple(
    pasimple.PA_STREAM_RECORD,
    FORMAT,
    CHANNELS,
    SAMPLE_RATE,
    device_name="<alsa_input.usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01.mono-fallback>",
) as pa:
    audio_data = pa.read(CHANNELS * SAMPLE_RATE * SAMPLE_WIDTH * 10)

# Save audio to a file
with wave.open("recording.wav", "wb") as wave_file:
    wave_file.setsampwidth(SAMPLE_WIDTH)
    wave_file.setnchannels(CHANNELS)
    wave_file.setframerate(SAMPLE_RATE)
    wave_file.writeframes(audio_data)
````

#### Device info
```bash
ubuntu@ubuntu:/workspace$ pacmd list-sources
4 source(s) available.
    index: 0
        name: <alsa_output.usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01.analog-stereo.monitor>
        driver: <module-alsa-card.c>
        flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 1040
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max rewind: 0 KiB
        sample spec: s16le 2ch 48000Hz
        channel map: front-left,front-right
                     Stereo
        used by: 0
        linked by: 0
        configured latency: 0.00 ms; range is 0.50 .. 2000.00 ms
        monitor_of: 0
        card: 1 <alsa_card.usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01>
        module: 8
        properties:
                device.description = "Monitor of MCP01 Analog Stereo"
                device.class = "monitor"
                alsa.card = "1"
                alsa.card_name = "MCP01"
                alsa.long_card_name = "Lenovo MCP01 at usb-3610000.usb-4.2, full speed"
                alsa.driver_name = "snd_usb_audio"
                device.bus_path = "platform-3610000.usb-usb-0:4.2:1.1"
                sysfs.path = "/devices/platform/bus@0/3610000.usb/usb1/1-4/1-4.2/1-4.2:1.1/sound/card1"
                udev.id = "usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01"
                device.bus = "usb"
                device.vendor.id = "17ef"
                device.vendor.name = "Lenovo"
                device.product.id = "a03b"
                device.product.name = "MCP01"
                device.serial = "Lenovo_MCP01_ACTIONS-DEV-SN1"
                device.string = "1"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-usb"
  * index: 1
        name: <alsa_input.usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01.mono-fallback>
        driver: <module-alsa-card.c>
        flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 9040
        volume: mono: 19097 /  29%
                balance 0.00
        base volume: 65536 / 100%
        volume steps: 152
        muted: no
        current latency: 0.00 ms
        max rewind: 0 KiB
        sample spec: s16le 1ch 48000Hz
        channel map: mono
                     Mono
        used by: 0
        linked by: 0
        configured latency: 0.00 ms; range is 0.50 .. 2000.00 ms
        card: 1 <alsa_card.usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01>
        module: 8
        properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "USB Audio"
                alsa.id = "USB Audio"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "1"
                alsa.card_name = "MCP01"
                alsa.long_card_name = "Lenovo MCP01 at usb-3610000.usb-4.2, full speed"
                alsa.driver_name = "snd_usb_audio"
                device.bus_path = "platform-3610000.usb-usb-0:4.2:1.1"
                sysfs.path = "/devices/platform/bus@0/3610000.usb/usb1/1-4/1-4.2/1-4.2:1.1/sound/card1"
                udev.id = "usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01"
                device.bus = "usb"
                device.vendor.id = "17ef"
                device.vendor.name = "Lenovo"
                device.product.id = "a03b"
                device.product.name = "MCP01"
                device.serial = "Lenovo_MCP01_ACTIONS-DEV-SN1"
                device.string = "hw:1"
                device.buffering.buffer_size = "192000"
                device.buffering.fragment_size = "96000"
                device.access_mode = "mmap+timer"
                device.profile.name = "mono-fallback"
                device.profile.description = "Mono"
                device.description = "MCP01 Mono"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-usb"
        ports:
                analog-input-mic: Microphone (priority 8700, latency offset 0 usec, available: unknown)
                        properties:
                                device.icon_name = "audio-input-microphone"
        active port: <analog-input-mic>
    index: 2
        name: <alsa_output.platform-sound.analog-stereo.monitor>
        driver: <module-alsa-card.c>
        flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 1000
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max rewind: 0 KiB
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        used by: 0
        linked by: 0
        configured latency: 0.00 ms; range is 0.50 .. 185.76 ms
        monitor_of: 1
        card: 2 <alsa_card.platform-sound>
        module: 9
        properties:
                device.description = "Monitor of Built-in Audio Analog Stereo"
                device.class = "monitor"
                alsa.card = "2"
                alsa.card_name = "NVIDIA Jetson AGX Orin APE"
                alsa.long_card_name = "NVIDIA-NVIDIAJetsonAGXOrinDeveloperKit-NotSpecified-Jetson"
                alsa.driver_name = "snd_soc_tegra_machine_driver"
                device.bus_path = "platform-sound"
                sysfs.path = "/devices/platform/sound/sound/card2"
                device.form_factor = "internal"
                device.string = "2"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card"
    index: 3
        name: <alsa_input.platform-sound.analog-stereo>
        driver: <module-alsa-card.c>
        flags: HARDWARE DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 9009
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max rewind: 0 KiB
        sample spec: s16le 2ch 48000Hz
        channel map: front-left,front-right
                     Stereo
        used by: 0
        linked by: 0
        configured latency: 0.00 ms; range is 0.50 .. 170.67 ms
        card: 2 <alsa_card.platform-sound>
        module: 9
        properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = ""
                alsa.id = "tegra-dlink-0 XBAR-ADMAIF1-0"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "2"
                alsa.card_name = "NVIDIA Jetson AGX Orin APE"
                alsa.long_card_name = "NVIDIA-NVIDIAJetsonAGXOrinDeveloperKit-NotSpecified-Jetson"
                alsa.driver_name = "snd_soc_tegra_machine_driver"
                device.bus_path = "platform-sound"
                sysfs.path = "/devices/platform/sound/sound/card2"
                device.form_factor = "internal"
                device.string = "front:2"
                device.buffering.buffer_size = "32768"
                device.buffering.fragment_size = "4096"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "Built-in Audio Analog Stereo"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card"
        ports:
                analog-input: Analog Input (priority 10000, latency offset 0 usec, available: unknown)
                        properties:

        active port: <analog-input>
```

**Comment by henrikschnor** [comment]
Have you tried removing the angle brackets from the device name?
`device_name="alsa_input.usb-Lenovo_MCP01_ACTIONS-DEV-SN1-01.mono-fallback",`

Otherwise, the script works fine on my machine if I insert one of my own device names:
```python
import wave
import pasimple

# Audio attributes for the recording
FORMAT = pasimple.PA_SAMPLE_U8
SAMPLE_WIDTH = pasimple.format2width(FORMAT)
CHANNELS = 1
SAMPLE_RATE = 48000

# Record 10 seconds of audio
with pasimple.PaSimple(
    pasimple.PA_STREAM_RECORD,
    FORMAT,
    CHANNELS,
    SAMPLE_RATE,
    device_name="alsa_input.pci-0000_06_00.6.HiFi__Mic1__source",
) as pa:
    audio_data = pa.read(CHANNELS * SAMPLE_RATE * SAMPLE_WIDTH * 10)

# Save audio to a file
with wave.open("recording.wav", "wb") as wave_file:
    wave_file.setsampwidth(SAMPLE_WIDTH)
    wave_file.setnchannels(CHANNELS)
    wave_file.setframerate(SAMPLE_RATE)
    wave_file.writeframes(audio_data)
```

Also, `PA_SAMPLE_S32LE` will give you better audio quality than `PA_SAMPLE_U8`. ;-)

**Comment by henry-tujia** [comment]
I have updated my code to the following:

```python
import wave
import pasimple

# Audio attributes for the recording
FORMAT = pasimple.PA_SAMPLE_S32LE
SAMPLE_WIDTH = pasimple.format2width(FORMAT)
CHANNELS = 1
SAMPLE_RATE = 48000

# Record 10 seconds of audio
with pasimple.PaSimple(
    pasimple.PA_STREAM_RECORD,
    FORMAT,
    CHANNELS,
    SAMPLE_RATE,
    device_name="alsa_input.usbe-Lenovo_MCP01_ACTIONS-DEV-SN1-01.mono-fallback",
) as pa:
    audio_data = pa.read(CHANNELS * SAMPLE_RATE * SAMPLE_WIDTH * 10)

# Save the audio to a file
with wave.open("recording.wav", "wb") as wave_file:
    wave_file.setsampwidth(SAMPLE_WIDTH)
    wave_file.setnchannels(CHANNELS)
    wave_file.setframerate(SAMPLE_RATE)
    wave_file.writeframes(audio_data)
```

However, after making this change, I encountered the following error:

```bash
Traceback (most recent call last):
  File "/workspace/carllm-test/tests/test_pasimple.py", line 11, in <module>
    with pasimple.PaSimple(
  File "/workspace/miniconda3/envs/whl_test/lib/python3.10/site-packages/pasimple/pa_simple.py", line 89, in __init__
    raise PaSimpleError(f'Error while creating stream: {error.value}')
pasimple.exceptions.PaSimpleError: Error while creating stream: 5
```

Perhaps you could help me understand what the error code `5` means, so I can check my Python environment accordingly.

**Comment by henrikschnor** [comment]
This is odd. There is a list of PulseAudio error codes in the readme. 5 means "no such entity" and there seems to be a [number of places within PulseAudio](https://gitlab.freedesktop.org/search?search=PA_ERR_NOENTITY&nav_source=navbar&project_id=810&group_id=1283&search_code=true&repository_ref=master) where this could be raised. I haven't run into this myself before.

Have you checked if the sound device you're using is working properly? I.e. can you see it in pavucontrol under "Input Devices" and can you see a spike there when you make a sound? Does recording in other apps (e.g. Audacity) work?

**Comment by henrikschnor** [comment]
From your output of `pacmd list-sources`, it seems like your device records in S16LE natively, maybe try using that format for recording as well. Other than that, I have no idea what could be wrong.

**Comment by henry-tujia** [comment]
Okay, it might be an issue with the microphone I have. I've previously encountered a situation where `pacmd list-sources` did not display the device. I appreciate your effort, but I will temporarily close this issue.
